### PR TITLE
Polymorphism

### PR DESCRIPTION
**Pull request by charlesfries**
- Generate base model for polymorphism
- Implement serializer methods
- Add tests

Questions
- Is there a better/simpler demonstration of polymorphism than just an event model that can belong to any `OwnerModel` subclass? That is all I could think of but I'm all ears.
- Should we add docs for this?

### CODE REVIEW

**Comment by charlesfries** [comment]
There is an issue with non-polymorphic serialization. Will take another look at this

**Comment by mikkopaderes** [comment]
Thanks for the good work here. I'll definitely review it by tomorrow 🥳

**Comment by charlesfries** [comment]
Sounds good! No rush at all

**Comment by mikkopaderes** [comment]
Reading on the polymorphic [docs](https://guides.emberjs.com/release/models/relationships/#toc_polymorphism) in Ember Data, it needs the data to be in a certain format in order to determine the polymorphic relationship.

How will this look like in a more flat structure for Firestore and how do you determine if it's polymorphic?

**Comment by charlesfries** [comment]
Mind elaborating a bit regarding your flat structure concern? Not sure if I totally get what you mean.

Regarding the format, we can determine the type using the collection name that's embedded in reference-type fields. Right now, types are determined by looking at the `belongsTo` model name (e.g. `@belongsTo('user')` should query the `users` collection and populate a `UserModel`). For `belongsTo` relationships that have the `{ polymorphic: true }` flag enabled, we can then instead switch over to using the collection name from the reference field to determine the narrower type, and therefore the collection and model class.

One thing I should mention is that there is nothing inherently polymorphic in Cloud Firestore. Whether a relationship is polymorphic or not is handled by abstraction in Ember Data.

**Comment by mikkopaderes** [comment]
@charlesfries, okay, I understand. But I don't think we want to use the reference fields as the means to determine the model type because it doesn't necessarily do so. The reference field can be pointed to somewhere else depending on how the data was structured, like a `PetModel` which can have a polymorphic of `DogModel` and `CatModel` can have reference field to `pets` collection which would be wrong now as we assumed that the collection would be `dogs` or `cats` respectively.

Also, I'm sorry about the flat structure, my terms might not be correct. But here's what I meant:

```json
"users": { // Root collection
  "user_1": { // Document
    "name": "John Doe",
    "pets": { // Sub-collection
      "pet_1": { // Document
        "name": "Cooper",
        "type": "Dog"
      },
      "pet_2": { // Document
        "name": "Rufus"
        "type": "Cat"
      },
    }
  }
}
```

I think it's possible to support a polymorphic `belongsTo` in that we could just follow the [`keyForPolymorphicType`](https://api.emberjs.com/ember-data/4.1/classes/RESTSerializer/methods/keyForPolymorphicType?anchor=keyForPolymorphicType) pattern from `RESTSerializer`. An example document could look like this:

```json
"users": {
  "user_1": {
    "name": "John Doe",
    "paymentMethod": <ref_to_payment_method>,
    "paymentMethodType": "paypal"
  }
}
```

In the example above, if our `keyForPolymorphicType` returns `paymentMethodType` then we'll be able to map that the polymorphic `paymentMethod` points to `PaymentMethodPaypalModel`.

However, for `hasMany`, I'm having a hard time being able to figure it out as we don't have any information on what polymorphic type it will be until we actually fetch the data and I believe that ember-data maps the polymorphic model before you do that fetching of `hasMany`.

**Comment by mikkopaderes** [comment]
I've been looking into this and my conclusion here is I don't want to implement a default way to handle polymorphism. What I'm looking into is if I can provide some overridable API in the serializer that can be used to setup polymorphism. But to be honest, I don't think that it's a good idea to use polymorphism even if the adapter is capable of doing it especially for large scale apps, let me explain.

In order for polymorphism to work, your data needs to have some indicator on what type of model this would be. It can look like this:

```json
{
  "id": "farm_1",
  "animals": [
    { "id": "pet_1", "type": "sheep" },
    { "id": "pet_2", "type": "cow" },
    { "id": "pet_3", "type": "cow" },
    { "id": "pet_4", "type": "chicken" },
  ]
}
```

The example above is for a has-many polymorphism. Imagine if you have that as a `Document` in Firestore, the `animals` field could have an infinite amount of data. If you fetch the `farm_1` document, you would have to download the **whole** `animals` field as well—you wouldn't have the ability to limit/paginate it. Not only will this be slow for your users, it will also cost you more especially if you have a listener setup on that document.

Granted that some may force their way into using polymorphism especially if they can guarantee that the has-many relationship wouldn't grow in size, this is something that I will try to look into. As mentioned above, the approach that I'd like to take is to provide APIs that developers will override in order to setup polymorphism based on how they structure the data in their Firestore project.

Thank you for starting the work here @charlesfries but I think that I'll close this PR for now as we need to find a different approach for this. If this works for you at the moment, then continue using it.

**Pull request closed without merging**
