### PR TITLE
Add support for FastBoot authentication

### LINKED ISSUE #99: Support FastBoot authentication
Firebase auth uses JWT tokens for authentication, not cookies. JWT tokens are short live so if we pass that in to the server through cookies and verify it, there's a high chance that it's already expired.

[Service workers](https://firebase.google.com/docs/auth/web/service-worker-sessions) might work although I haven't tried this solution yet.

Here's the flow of I think FastBoot auth could work:

1. Have a service worker that intercepts `fetch` and modify to add the result of [`getIdToken()`](https://firebase.google.com/docs/reference/js/firebase.User#get-idtoken)
2. In FastBoot server, verify the token through [`verifyIdToken()`](https://firebase.google.com/docs/reference/admin/node/admin.auth.Auth.html#verifyidtoken).
3. Once the verification succeeds, we generate a custom token through [`createCustomToken()`](https://firebase.google.com/docs/reference/admin/node/admin.auth.Auth.html#create-custom-token).
4. We then pass-in the custom token in the request header to Ember FastBoot (maybe in Authorization header?)
5. In Ember FastBoot, we [access the token through the header](http://ember-fastboot.com/docs/user-guide#access-request-headers) and use it in the ESA authenticator [`restore()`](https://github.com/mikkopaderes/ember-cloud-firestore-adapter/blob/master/addon/authenticators/firebase.js#L45) hook. We'll be using [`signInWithCustomToken()`](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#sign-inwith-custom-token) to finally sign in the user.

This addon can support points 1 and 5 although I'm still contemplating if we should have 1 built-in. Points 2, 3, and 4 would have to be done in the FastBoot server which is out of our control.

### PR DESCRIPTION
**Pull request by mikkopaderes**
Resolves #99

### CODE REVIEW

**Comment by alexmasita** [comment]
@mikkopaderes.  Clearly the works of masters!  Have you merged this?

**Comment by mikkopaderes** [comment]
Still a work in progress (WIP). I still need to add the service worker part and test if things actually work.

**Comment by mikkopaderes** [comment]
Holding off this PR until this firebase/firebase-js-sdk#1906 gets resolved.

I'm unable to use any version lower than 6.2.2 in a Node environment as I'm getting `not a function` error for both `firebase.firestore()` and `firebase.auth()`. Not sure why.

**Comment by alexmasita** [comment]
@mikkopaderes Thanks for your efforts to resolve this.  Let us see what happens with the firebase bug ...

**Comment by alexmasita** [comment]
Thank you for your work on this.  I see on the documentation you show how to set up the server side to authenticate in fastboot which is great.  How though do you test this while in development as I assume when you ember serve, ember cli starts the 'hidden' fastboot server on your behalf?  Let me know.

**Comment by mikkopaderes** [comment]
@alexmasita

I don't use fastboot app server but from the look of things you'd insert that at the [before middleware hook](https://github.com/ember-fastboot/fastboot-app-server/blob/master/README.md#pre-and-post-fastboot-middleware-hooks).

**Comment by alexmasita** [comment]
@mikkopaderes Thank you for that.  For the most part, I have everything set up.  I am having trouble getting a valid token as I am getting the following error:

```
[2019-06-30T20:35:44.386Z][w83622] starting HTTP server
[2019-06-30T20:35:44.402Z][w83622] HTTP server started; url=http://:::8000
firebase verifyID Token get entered
idToken:  Error: Your API key is invalid, please check you have copied it correctly.
firebase verifyID Token error
{ Error: Decoding Firebase ID token failed. Make sure you passed the entire string JWT which represents an ID token. See https://firebase.google.com/docs/auth/admin/verify-id-tokens for details on how to retrieve an ID token.
    at FirebaseAuthError.FirebaseError [as constructor] (/Users/alexmasita/External/Personal/projects/Ember-Apps/3.10/ember310/node_modules/firebase-admin/lib/utils/error.js:42:28)
    at FirebaseAuthError.PrefixedFirebaseError [as constructor] (/Users/alexmasita/External/Personal/projects/Ember-Apps/3.10/ember310/node_modules/firebase-admin/lib/utils/error.js:88:28)
    at new FirebaseAuthError (/Users/alexmasita/External/Personal/projects/Ember-Apps/3.10/ember310/node_modules/firebase-admin/lib/utils/error.js:146:16)
    at FirebaseTokenVerifier.verifyJWT (/Users/alexmasita/External/Personal/projects/Ember-Apps/3.10/ember310/node_modules/firebase-admin/lib/auth/token-verifier.js:158:35)
    at Auth.BaseAuth.verifyIdToken (/Users/alexmasita/External/Personal/projects/Ember-Apps/3.10/ember310/node_modules/firebase-admin/lib/auth/auth.js:105:37)
    at app.get (/Users/alexmasita/External/Personal/projects/Ember-Apps/3.10/ember310/fastboot/main.js:20:45)
    at Layer.handle [as handle_request] (/Users/alexmasita/External/Personal/projects/Ember-Apps/3.10/ember310/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/alexmasita/External/Personal/projects/Ember-Apps/3.10/ember310/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/alexmasita/External/Personal/projects/Ember-Apps/3.10/ember310/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/alexmasita/External/Personal/projects/Ember-Apps/3.10/ember310/node_modules/express/lib/router/layer.js:95:5)
  errorInfo:
   { code: 'auth/argument-error',
     message:
      'Decoding Firebase ID token failed. Make sure you passed the entire string JWT which represents an ID token. See https://firebase.google.com/docs/auth/admin/verify-id-tokens for details on how to retrieve an ID token.' },
  codePrefix: 'auth' }
Overwriting FirebaseError base field "name" can cause unexpected behavior.
DEBUG: The authenticator "authenticator:firebase" rejected to restore the session - invalidating…
application route activated
2019-06-30T20:36:00.648Z 307 OK /protected
```
I looked at your repo dummy app to see if I had missed anything but could not see anything that could help me resolve my issue.
So I tried to drill for the issue and found my way into this addon's service worker file and put some console.log calls inside `getIdToken()` method as seen here:

```
function getIdToken() {
  console.log('Line 1 - Service Worker getIdToken Method Called');

  return new Promise((resolve) => {
    console.log('Line 2 - Service Worker getIdToken Promise Returned');
    const unsubscribe = firebase.auth().onAuthStateChanged((user) => {
      unsubscribe();
      console.log('Line 3 - Service Worker onAuthStateChanged Callback Called', idToken);
      console.log('Line 4 - Service Worker User Object');
      console.log(user);
      if (user) {
        user.getIdToken().then(idToken => {
          console.log('Line 5 - Service Worker user.getIdToken Promise Returned', idToken);
          resolve(idToken);
        }).catch(() => resolve(null));
      } else {
        resolve(null);
      }
    });
  });
};
```
I found that as seen on this screenshot: [Browser Console Snapshot](http://prntscr.com/o8qp94), only line 1 and line 2 are logged to the console meaning that the `user.getIdToken()` never actually gets called on my end.

I created a completely fresh repo for this test which you can even pull, run and see for yourself if you have time: [Firebase Authentication Sample Repo](https://github.com/alexmasita/Firebase-Authentication-Sample.git).

Thank you for all your time on this.

**Comment by mikkopaderes** [comment]
`Line 2: idToken: Error: Your API key is invalid, please check you have copied it correctly.`

Basing on the code snippet above, this doesn't look right. It should display the token, not some string message. What is the value of `request.headers.authorization`?

Your test repo is also 404.

**Comment by alexmasita** [comment]
I have added a log call as seen here:

```
let server = new FastBootAppServer({
  beforeMiddleware: function (app) {
    app.get('/*', async (req, res, next) => {
      console.log('Line 1: firebase verifyID Token get entered');
      console.log('Line 1.1: firebase req.headers.authorization');
      console.log(req.headers.authorization);
      if (req.headers.authorization && req.headers.authorization.startsWith('Bearer ')) {
        try {
          const idToken = req.headers.authorization.split('Bearer ')[1];
          console.log('Line 2: idToken: ', idToken);
          const auth = admin.auth();
          const decodedIdToken = await auth.verifyIdToken(idToken);
          const {
            uid
          } = decodedIdToken;
          const customToken = await auth.createCustomToken(uid);
          console.log('Line 3: firebase customToken: ', customToken);
          req.headers.authorization = `Bearer ${customToken}`;
        } catch (error) {
          console.log('Line 4: firebase Token error');
          console.log(error);
        }
      }

      next();
    });
  },
  distPath: 'dist',
  gzip: true
});
```
The result of this: `console.log(req.headers.authorization);` is `undefined`.

I have made the [Firebase Authentication Sample Repo](https://github.com/alexmasita/Firebase-Authentication-Sample.git) public.  Sorry for the oversight.

**Comment by mikkopaderes** [comment]
I won't be able to check on this yet. But quickly looking at things, I don't see Firebase as a devDependency to your ember app.

Can you try adding it?

**Comment by alexmasita** [comment]
Yes!  What a somewhat obvious omission that was?!  Done it and still the same issue here though.

**Comment by mikkopaderes** [comment]
Thanks for the report. See #101 for the fix.

**Comment by alexmasita** [comment]
Great.  I can confirm the issue is resolved from my end.  Thank you.

**Pull request merged**
