### PR TITLE
Add support for using Firebase Emulator

### PR DESCRIPTION
**Pull request by mikkopaderes**
This PR adds support for using the Firebase Emulator introduced in Firebase `v8.0.0`. To set it up, in your `config/environment.js`, you need to set:

```javascript
let ENV = {
  ...

  'ember-cloud-firestore-adapter': {
    emulator: {
      hostname: 'localhost',
      port: 8080
    },
  },

  ...
}
```

Feel free to use a different `hostname` and `port` depending on your setup.

Aside from the changes above, this addon itself is now setup to utilize Firebase Emulator for local development and testing.

### CODE REVIEW

**Comment by mikkopaderes** [comment]
Firebase Emulator is failing in Travis. I dunno why... 😕

**Comment by conormag** [comment]
Took a while but I think i got to the bottom of it. I think you're working in a windows environment? It looks like the filepaths in the emulator-data/firestore_export.overall-export-metadata have backslashes for part of the path. I used the method here https://github.com/firebase/firebase-tools/issues/2421 to generate a new emulator-data folder and it no longer crashes although the tests fail

**Comment by mikkopaderes** [comment]
> 
> 
> Took a while but I think i got to the bottom of it. I think you're working in a windows environment? It looks like the filepaths in the emulator-data/firestore_export.overall-export-metadata have backslashes for part of the path. I used the method here [firebase/firebase-tools#2421](https://github.com/firebase/firebase-tools/issues/2421) to generate a new emulator-data folder and it no longer crashes although the tests fail

Woah, thanks for looking into it. Hmm, so this means that my `emulator-data` wouldn't work on non-Windows machine. Well that's a let down. I hope they manage to fix the bug soon.

Also, I didn't quite understand the instructions in [this](https://github.com/firebase/firebase-tools/issues/2421#issuecomment-702517779). What's the previous dir he's talking about?

**Comment by conormag** [comment]
The previous folder he was referencing was the one containing the files
with the backslash paths. I think this solution was only meant to be a
temporary workaround of course.

**Pull request merged**
